### ISSUE TITLE
Varnish 6.0

### ISSUE THREAD

**Issue by helmerfud** [wikimedia/varnishkafka#59]
Hello,
i just discover your project and i have varnish v6.0 in test.
Is varnishkafka compatible with varnish 6 ?

thank you.
Best regards.

**Comment by elukey** [comment]
Hi! Thanks for reaching out. At the moment we are running Varnish 5.1 in Wikimedia, but due to a big change in the shared log APIs with 5.2+, varnishkafka doesn't even compile with recent versions of Varnish. There is some work in https://gerrit.wikimedia.org/r/#/c/430069/ to make varnishkafka work with 5.2+, but we still need to test it properly (if you want to do it and report back it would be really awesome).

Last but not the least: we use github only as a mirror for gerrit.wikimedia.org, this is why I didn't show you a pull request but the above link :)

**Comment by elukey** [comment]
The last version in master is compatible with Varnish 5.2 to 6.x, any feedback/test is welcome :)
